// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: electricity_record.sql

package db

import (
	"context"
	"time"
)

const createElectricityRecord = `-- name: CreateElectricityRecord :one
INSERT INTO electricity_records (
    room_id, balance
) VALUES (
    $1, $2
)
RETURNING id, room_id, balance, recorded_at
`

type CreateElectricityRecordParams struct {
	RoomID  int64 `json:"room_id"`
	Balance int64 `json:"balance"`
}

// 插入一条电费记录
func (q *Queries) CreateElectricityRecord(ctx context.Context, arg CreateElectricityRecordParams) (ElectricityRecord, error) {
	row := q.db.QueryRowContext(ctx, createElectricityRecord, arg.RoomID, arg.Balance)
	var i ElectricityRecord
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Balance,
		&i.RecordedAt,
	)
	return i, err
}

const createElectricityRecordwithTime = `-- name: CreateElectricityRecordwithTime :one
INSERT INTO electricity_records (
    room_id, balance, recorded_at
) VALUES (
    $1, $2, $3
)
RETURNING id, room_id, balance, recorded_at
`

type CreateElectricityRecordwithTimeParams struct {
	RoomID     int64     `json:"room_id"`
	Balance    int64     `json:"balance"`
	RecordedAt time.Time `json:"recorded_at"`
}

// 用于插入测试数据的电费记录
func (q *Queries) CreateElectricityRecordwithTime(ctx context.Context, arg CreateElectricityRecordwithTimeParams) (ElectricityRecord, error) {
	row := q.db.QueryRowContext(ctx, createElectricityRecordwithTime, arg.RoomID, arg.Balance, arg.RecordedAt)
	var i ElectricityRecord
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Balance,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestBalance = `-- name: GetLatestBalance :one
SELECT id, room_id, balance, recorded_at FROM electricity_records
WHERE room_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

// 获取最新的余额记录
func (q *Queries) GetLatestBalance(ctx context.Context, roomID int64) (ElectricityRecord, error) {
	row := q.db.QueryRowContext(ctx, getLatestBalance, roomID)
	var i ElectricityRecord
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Balance,
		&i.RecordedAt,
	)
	return i, err
}

const getRecordsByHourRange = `-- name: GetRecordsByHourRange :many
SELECT id, room_id, balance, recorded_at FROM electricity_records
WHERE room_id = $1 
  AND recorded_at BETWEEN $2 AND $3
ORDER BY recorded_at ASC
`

type GetRecordsByHourRangeParams struct {
	RoomID    int64     `json:"room_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// 获取指定时间范围内的每小时记录
func (q *Queries) GetRecordsByHourRange(ctx context.Context, arg GetRecordsByHourRangeParams) ([]ElectricityRecord, error) {
	rows, err := q.db.QueryContext(ctx, getRecordsByHourRange, arg.RoomID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ElectricityRecord{}
	for rows.Next() {
		var i ElectricityRecord
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Balance,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
