// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

// 存储抓取的电费流水数据
type ElectricityRecord struct {
	ID         int64     `json:"id"`
	RoomID     int64     `json:"room_id"`
	Balance    int64     `json:"balance"`
	RecordedAt time.Time `json:"recorded_at"`
}

// 存储需要监控的寝室配置信息
type Room struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	AreaID       string    `json:"area_id"`
	BuildingCode string    `json:"building_code"`
	FloorCode    string    `json:"floor_code"`
	RoomCode     string    `json:"room_code"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
}
