// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// 统计寝室总数
	CountRooms(ctx context.Context) (int64, error)
	// 插入一条电费记录
	CreateElectricityRecord(ctx context.Context, arg CreateElectricityRecordParams) (ElectricityRecord, error)
	// 用于插入测试数据的电费记录
	CreateElectricityRecordwithTime(ctx context.Context, arg CreateElectricityRecordwithTimeParams) (ElectricityRecord, error)
	// 插入一个要查询的寝室信息
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	// 删除寝室信息
	DeleteRoom(ctx context.Context, id int64) error
	// 获取最新的余额记录
	GetLatestBalance(ctx context.Context, roomID int64) (ElectricityRecord, error)
	// 获取指定时间范围内的每小时记录
	GetRecordsByHourRange(ctx context.Context, arg GetRecordsByHourRangeParams) ([]ElectricityRecord, error)
	// 根据ID查询寝室信息
	GetRoom(ctx context.Context, id int64) (Room, error)
	// 分页查询所有寝室信息
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	// 查询所有寝室信息
	ListRoomsAll(ctx context.Context) ([]Room, error)
	// 更新寝室信息
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
