// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package db

import (
	"context"
	"database/sql"
)

const countRooms = `-- name: CountRooms :one
SELECT count(*) FROM rooms
`

// 统计寝室总数
func (q *Queries) CountRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
  name, area_id, building_code, floor_code, room_code
) VALUES (
 $1, $2, $3, $4, $5
)
RETURNING id, name, area_id, building_code, floor_code, room_code, created_at
`

type CreateRoomParams struct {
	Name         string `json:"name"`
	AreaID       string `json:"area_id"`
	BuildingCode string `json:"building_code"`
	FloorCode    string `json:"floor_code"`
	RoomCode     string `json:"room_code"`
}

// 插入一个要查询的寝室信息
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.AreaID,
		arg.BuildingCode,
		arg.FloorCode,
		arg.RoomCode,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.BuildingCode,
		&i.FloorCode,
		&i.RoomCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1
`

// 删除寝室信息
func (q *Queries) DeleteRoom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, area_id, building_code, floor_code, room_code, created_at FROM rooms
WHERE id = $1 LIMIT 1
`

// 根据ID查询寝室信息
func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.BuildingCode,
		&i.FloorCode,
		&i.RoomCode,
		&i.CreatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, area_id, building_code, floor_code, room_code, created_at FROM rooms
ORDER BY name
LIMIT $1 
OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 分页查询所有寝室信息
func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AreaID,
			&i.BuildingCode,
			&i.FloorCode,
			&i.RoomCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsAll = `-- name: ListRoomsAll :many
SELECT id, name, area_id, building_code, floor_code, room_code, created_at FROM rooms
ORDER BY name
`

// 查询所有寝室信息
func (q *Queries) ListRoomsAll(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AreaID,
			&i.BuildingCode,
			&i.FloorCode,
			&i.RoomCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = coalesce($2, name),
    area_id = coalesce($3, area_id),
    building_code = coalesce($4, building_code),
    floor_code = coalesce($5, floor_code),
    room_code = coalesce($6, room_code)
WHERE id = $1
RETURNING id, name, area_id, building_code, floor_code, room_code, created_at
`

type UpdateRoomParams struct {
	ID           int64          `json:"id"`
	Name         sql.NullString `json:"name"`
	AreaID       sql.NullString `json:"area_id"`
	BuildingCode sql.NullString `json:"building_code"`
	FloorCode    sql.NullString `json:"floor_code"`
	RoomCode     sql.NullString `json:"room_code"`
}

// 更新寝室信息
func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.AreaID,
		arg.BuildingCode,
		arg.FloorCode,
		arg.RoomCode,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaID,
		&i.BuildingCode,
		&i.FloorCode,
		&i.RoomCode,
		&i.CreatedAt,
	)
	return i, err
}
