// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_rooms.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoomsByUser = `-- name: CountRoomsByUser :one
SELECT count(*) FROM user_rooms 
WHERE username = $1
`

// 统计用户绑定的寝室总数
func (q *Queries) CountRoomsByUser(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomsByUser, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserRooms = `-- name: CountUserRooms :one
SELECT COUNT(*) FROM user_rooms
`

// 统计user-rooms表的关联总数
func (q *Queries) CountUserRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserRoom = `-- name: CreateUserRoom :one
INSERT INTO user_rooms (
	username, room_id, threshold, is_enabled
) VALUES (
	$1, $2, $3, $4
)
RETURNING username, room_id, threshold, is_enabled, last_notified_at
`

type CreateUserRoomParams struct {
	Username  string `json:"username"`
	RoomID    int64  `json:"room_id"`
	Threshold int32  `json:"threshold"`
	IsEnabled bool   `json:"is_enabled"`
}

// 创建用户-寝室关联
func (q *Queries) CreateUserRoom(ctx context.Context, arg CreateUserRoomParams) (UserRoom, error) {
	row := q.db.QueryRow(ctx, createUserRoom,
		arg.Username,
		arg.RoomID,
		arg.Threshold,
		arg.IsEnabled,
	)
	var i UserRoom
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}

const deleteUserRoom = `-- name: DeleteUserRoom :exec
DELETE FROM user_rooms
WHERE username = $1
	AND room_id = $2
`

type DeleteUserRoomParams struct {
	Username string `json:"username"`
	RoomID   int64  `json:"room_id"`
}

// 删除关联
func (q *Queries) DeleteUserRoom(ctx context.Context, arg DeleteUserRoomParams) error {
	_, err := q.db.Exec(ctx, deleteUserRoom, arg.Username, arg.RoomID)
	return err
}

const getUserRoom = `-- name: GetUserRoom :one
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_rooms
WHERE username = $1
	AND room_id = $2
LIMIT 1
`

type GetUserRoomParams struct {
	Username string `json:"username"`
	RoomID   int64  `json:"room_id"`
}

// 查询单个关联
func (q *Queries) GetUserRoom(ctx context.Context, arg GetUserRoomParams) (UserRoom, error) {
	row := q.db.QueryRow(ctx, getUserRoom, arg.Username, arg.RoomID)
	var i UserRoom
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}

const listDueUserRooms = `-- name: ListDueUserRooms :many
SELECT username, room_id, threshold 
FROM user_rooms 
WHERE is_enabled = true 
  AND last_notified_at < (now() - interval '24 hours')
`

type ListDueUserRoomsRow struct {
	Username  string `json:"username"`
	RoomID    int64  `json:"room_id"`
	Threshold int32  `json:"threshold"`
}

// 查询需要发送通知的关联（开启且上次通知时间超过 24 小时）
func (q *Queries) ListDueUserRooms(ctx context.Context) ([]ListDueUserRoomsRow, error) {
	rows, err := q.db.Query(ctx, listDueUserRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueUserRoomsRow{}
	for rows.Next() {
		var i ListDueUserRoomsRow
		if err := rows.Scan(&i.Username, &i.RoomID, &i.Threshold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRooms = `-- name: ListUserRooms :many
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_rooms
ORDER BY username ASC, room_id ASC
LIMIT $1
OFFSET $2
`

type ListUserRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 分页查询关联
func (q *Queries) ListUserRooms(ctx context.Context, arg ListUserRoomsParams) ([]UserRoom, error) {
	rows, err := q.db.Query(ctx, listUserRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoom{}
	for rows.Next() {
		var i UserRoom
		if err := rows.Scan(
			&i.Username,
			&i.RoomID,
			&i.Threshold,
			&i.IsEnabled,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoomsByRoom = `-- name: ListUserRoomsByRoom :many
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_rooms
WHERE room_id = $1
ORDER BY username ASC
`

// 查询某个寝室的全部关联
func (q *Queries) ListUserRoomsByRoom(ctx context.Context, roomID int64) ([]UserRoom, error) {
	rows, err := q.db.Query(ctx, listUserRoomsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoom{}
	for rows.Next() {
		var i UserRoom
		if err := rows.Scan(
			&i.Username,
			&i.RoomID,
			&i.Threshold,
			&i.IsEnabled,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoomsByUser = `-- name: ListUserRoomsByUser :many
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_rooms
WHERE username = $1
ORDER BY room_id ASC
LIMIT $2
OFFSET $3
`

type ListUserRoomsByUserParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

// 查询某个用户的全部关联
func (q *Queries) ListUserRoomsByUser(ctx context.Context, arg ListUserRoomsByUserParams) ([]UserRoom, error) {
	rows, err := q.db.Query(ctx, listUserRoomsByUser, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoom{}
	for rows.Next() {
		var i UserRoom
		if err := rows.Scan(
			&i.Username,
			&i.RoomID,
			&i.Threshold,
			&i.IsEnabled,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRoom = `-- name: UpdateUserRoom :one
UPDATE user_rooms
SET threshold = coalesce($3, threshold),
	is_enabled = coalesce($4, is_enabled)
WHERE username = $1
	AND room_id = $2
RETURNING username, room_id, threshold, is_enabled, last_notified_at
`

type UpdateUserRoomParams struct {
	Username  string      `json:"username"`
	RoomID    int64       `json:"room_id"`
	Threshold pgtype.Int4 `json:"threshold"`
	IsEnabled pgtype.Bool `json:"is_enabled"`
}

// 更新关联阈值和开关
func (q *Queries) UpdateUserRoom(ctx context.Context, arg UpdateUserRoomParams) (UserRoom, error) {
	row := q.db.QueryRow(ctx, updateUserRoom,
		arg.Username,
		arg.RoomID,
		arg.Threshold,
		arg.IsEnabled,
	)
	var i UserRoom
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}

const updateUserRoomLastNotifiedAt = `-- name: UpdateUserRoomLastNotifiedAt :one
UPDATE user_rooms
SET last_notified_at = $3
WHERE username = $1
	AND room_id = $2
RETURNING username, room_id, threshold, is_enabled, last_notified_at
`

type UpdateUserRoomLastNotifiedAtParams struct {
	Username       string    `json:"username"`
	RoomID         int64     `json:"room_id"`
	LastNotifiedAt time.Time `json:"last_notified_at"`
}

// 更新最后通知时间
func (q *Queries) UpdateUserRoomLastNotifiedAt(ctx context.Context, arg UpdateUserRoomLastNotifiedAtParams) (UserRoom, error) {
	row := q.db.QueryRow(ctx, updateUserRoomLastNotifiedAt, arg.Username, arg.RoomID, arg.LastNotifiedAt)
	var i UserRoom
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}
