// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_room_notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUserRoomNotifications = `-- name: CountUserRoomNotifications :one
SELECT COUNT(*) FROM user_room_notifications
`

// 统计通知订阅总数
func (q *Queries) CountUserRoomNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserRoomNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserRoomNotification = `-- name: CreateUserRoomNotification :one
INSERT INTO user_room_notifications (
	username, room_id, threshold
) VALUES (
	$1, $2, $3
)
RETURNING username, room_id, threshold, is_enabled, last_notified_at
`

type CreateUserRoomNotificationParams struct {
	Username  string `json:"username"`
	RoomID    int64  `json:"room_id"`
	Threshold int32  `json:"threshold"`
}

// 创建用户-寝室通知订阅
func (q *Queries) CreateUserRoomNotification(ctx context.Context, arg CreateUserRoomNotificationParams) (UserRoomNotification, error) {
	row := q.db.QueryRowContext(ctx, createUserRoomNotification, arg.Username, arg.RoomID, arg.Threshold)
	var i UserRoomNotification
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}

const deleteUserRoomNotification = `-- name: DeleteUserRoomNotification :exec
DELETE FROM user_room_notifications
WHERE username = $1
	AND room_id = $2
`

type DeleteUserRoomNotificationParams struct {
	Username string `json:"username"`
	RoomID   int64  `json:"room_id"`
}

// 删除通知订阅
func (q *Queries) DeleteUserRoomNotification(ctx context.Context, arg DeleteUserRoomNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserRoomNotification, arg.Username, arg.RoomID)
	return err
}

const getUserRoomNotification = `-- name: GetUserRoomNotification :one
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_room_notifications
WHERE username = $1
	AND room_id = $2
LIMIT 1
`

type GetUserRoomNotificationParams struct {
	Username string `json:"username"`
	RoomID   int64  `json:"room_id"`
}

// 查询单个通知订阅
func (q *Queries) GetUserRoomNotification(ctx context.Context, arg GetUserRoomNotificationParams) (UserRoomNotification, error) {
	row := q.db.QueryRowContext(ctx, getUserRoomNotification, arg.Username, arg.RoomID)
	var i UserRoomNotification
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}

const listDueUserRoomNotifications = `-- name: ListDueUserRoomNotifications :many
SELECT username, room_id, threshold 
FROM user_room_notifications 
WHERE is_enabled = true 
  AND last_notified_at < (now() - interval '24 hours')
`

type ListDueUserRoomNotificationsRow struct {
	Username  string `json:"username"`
	RoomID    int64  `json:"room_id"`
	Threshold int32  `json:"threshold"`
}

// 查询需要发送通知的订阅（开启且上次通知时间超过 24 小时）
func (q *Queries) ListDueUserRoomNotifications(ctx context.Context) ([]ListDueUserRoomNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueUserRoomNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueUserRoomNotificationsRow{}
	for rows.Next() {
		var i ListDueUserRoomNotificationsRow
		if err := rows.Scan(&i.Username, &i.RoomID, &i.Threshold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoomNotifications = `-- name: ListUserRoomNotifications :many
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_room_notifications
ORDER BY username ASC, room_id ASC
LIMIT $1
OFFSET $2
`

type ListUserRoomNotificationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 分页查询通知订阅
func (q *Queries) ListUserRoomNotifications(ctx context.Context, arg ListUserRoomNotificationsParams) ([]UserRoomNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoomNotifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoomNotification{}
	for rows.Next() {
		var i UserRoomNotification
		if err := rows.Scan(
			&i.Username,
			&i.RoomID,
			&i.Threshold,
			&i.IsEnabled,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoomNotificationsByRoom = `-- name: ListUserRoomNotificationsByRoom :many
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_room_notifications
WHERE room_id = $1
ORDER BY username ASC
`

// 查询某个寝室的全部通知订阅
func (q *Queries) ListUserRoomNotificationsByRoom(ctx context.Context, roomID int64) ([]UserRoomNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoomNotificationsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoomNotification{}
	for rows.Next() {
		var i UserRoomNotification
		if err := rows.Scan(
			&i.Username,
			&i.RoomID,
			&i.Threshold,
			&i.IsEnabled,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoomNotificationsByUser = `-- name: ListUserRoomNotificationsByUser :many
SELECT username, room_id, threshold, is_enabled, last_notified_at FROM user_room_notifications
WHERE username = $1
ORDER BY room_id ASC
`

// 查询某个用户的全部通知订阅
func (q *Queries) ListUserRoomNotificationsByUser(ctx context.Context, username string) ([]UserRoomNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoomNotificationsByUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoomNotification{}
	for rows.Next() {
		var i UserRoomNotification
		if err := rows.Scan(
			&i.Username,
			&i.RoomID,
			&i.Threshold,
			&i.IsEnabled,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRoomNotification = `-- name: UpdateUserRoomNotification :one
UPDATE user_room_notifications
SET threshold = coalesce($3, threshold),
	is_enabled = coalesce($4, is_enabled)
WHERE username = $1
	AND room_id = $2
RETURNING username, room_id, threshold, is_enabled, last_notified_at
`

type UpdateUserRoomNotificationParams struct {
	Username  string        `json:"username"`
	RoomID    int64         `json:"room_id"`
	Threshold sql.NullInt32 `json:"threshold"`
	IsEnabled sql.NullBool  `json:"is_enabled"`
}

// 更新通知阈值和开关
func (q *Queries) UpdateUserRoomNotification(ctx context.Context, arg UpdateUserRoomNotificationParams) (UserRoomNotification, error) {
	row := q.db.QueryRowContext(ctx, updateUserRoomNotification,
		arg.Username,
		arg.RoomID,
		arg.Threshold,
		arg.IsEnabled,
	)
	var i UserRoomNotification
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}

const updateUserRoomNotificationLastNotifiedAt = `-- name: UpdateUserRoomNotificationLastNotifiedAt :one
UPDATE user_room_notifications
SET last_notified_at = $3
WHERE username = $1
	AND room_id = $2
RETURNING username, room_id, threshold, is_enabled, last_notified_at
`

type UpdateUserRoomNotificationLastNotifiedAtParams struct {
	Username       string    `json:"username"`
	RoomID         int64     `json:"room_id"`
	LastNotifiedAt time.Time `json:"last_notified_at"`
}

// 更新最后通知时间
func (q *Queries) UpdateUserRoomNotificationLastNotifiedAt(ctx context.Context, arg UpdateUserRoomNotificationLastNotifiedAtParams) (UserRoomNotification, error) {
	row := q.db.QueryRowContext(ctx, updateUserRoomNotificationLastNotifiedAt, arg.Username, arg.RoomID, arg.LastNotifiedAt)
	var i UserRoomNotification
	err := row.Scan(
		&i.Username,
		&i.RoomID,
		&i.Threshold,
		&i.IsEnabled,
		&i.LastNotifiedAt,
	)
	return i, err
}
