// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jingqi0327/eleclog/worker (interfaces: TaskDistributor)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	worker "github.com/Jingqi0327/eleclog/worker"
	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskDetectLowBalance mocks base method.
func (m *MockTaskDistributor) DistributeTaskDetectLowBalance(arg0 context.Context, arg1 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskDetectLowBalance", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskDetectLowBalance indicates an expected call of DistributeTaskDetectLowBalance.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskDetectLowBalance(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskDetectLowBalance", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskDetectLowBalance), varargs...)
}

// DistributeTaskFetchSurplusAndStore mocks base method.
func (m *MockTaskDistributor) DistributeTaskFetchSurplusAndStore(arg0 context.Context, arg1 *worker.PayloadFetchSurplusAndStore, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskFetchSurplusAndStore", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskFetchSurplusAndStore indicates an expected call of DistributeTaskFetchSurplusAndStore.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskFetchSurplusAndStore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskFetchSurplusAndStore", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskFetchSurplusAndStore), varargs...)
}

// DistributeTaskSendFetchSurplusTasks mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendFetchSurplusTasks(arg0 context.Context, arg1 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendFetchSurplusTasks", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendFetchSurplusTasks indicates an expected call of DistributeTaskSendFetchSurplusTasks.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendFetchSurplusTasks(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendFetchSurplusTasks", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendFetchSurplusTasks), varargs...)
}

// DistributeTaskSendNotificationEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendNotificationEmail(arg0 context.Context, arg1 *worker.PayloadSendNotificationEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendNotificationEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendNotificationEmail indicates an expected call of DistributeTaskSendNotificationEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendNotificationEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendNotificationEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendNotificationEmail), varargs...)
}
