// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc_query_room.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	BuildingCode  string                 `protobuf:"bytes,2,opt,name=building_code,json=buildingCode,proto3" json:"building_code,omitempty"`
	FloorCode     string                 `protobuf:"bytes,3,opt,name=floor_code,json=floorCode,proto3" json:"floor_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoomRequest) Reset() {
	*x = QueryRoomRequest{}
	mi := &file_rpc_query_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoomRequest) ProtoMessage() {}

func (x *QueryRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoomRequest.ProtoReflect.Descriptor instead.
func (*QueryRoomRequest) Descriptor() ([]byte, []int) {
	return file_rpc_query_room_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRoomRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *QueryRoomRequest) GetBuildingCode() string {
	if x != nil {
		return x.BuildingCode
	}
	return ""
}

func (x *QueryRoomRequest) GetFloorCode() string {
	if x != nil {
		return x.FloorCode
	}
	return ""
}

type QueryRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // 原始的 JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoomResponse) Reset() {
	*x = QueryRoomResponse{}
	mi := &file_rpc_query_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoomResponse) ProtoMessage() {}

func (x *QueryRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoomResponse.ProtoReflect.Descriptor instead.
func (*QueryRoomResponse) Descriptor() ([]byte, []int) {
	return file_rpc_query_room_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRoomResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_rpc_query_room_proto protoreflect.FileDescriptor

const file_rpc_query_room_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_query_room.proto\x12\x02pb\"o\n" +
	"\x10QueryRoomRequest\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\x12#\n" +
	"\rbuilding_code\x18\x02 \x01(\tR\fbuildingCode\x12\x1d\n" +
	"\n" +
	"floor_code\x18\x03 \x01(\tR\tfloorCode\"0\n" +
	"\x11QueryRoomResponse\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonDataB\"Z github.com/Jingqi0327/eleclog/pbb\x06proto3"

var (
	file_rpc_query_room_proto_rawDescOnce sync.Once
	file_rpc_query_room_proto_rawDescData []byte
)

func file_rpc_query_room_proto_rawDescGZIP() []byte {
	file_rpc_query_room_proto_rawDescOnce.Do(func() {
		file_rpc_query_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_query_room_proto_rawDesc), len(file_rpc_query_room_proto_rawDesc)))
	})
	return file_rpc_query_room_proto_rawDescData
}

var file_rpc_query_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_query_room_proto_goTypes = []any{
	(*QueryRoomRequest)(nil),  // 0: pb.QueryRoomRequest
	(*QueryRoomResponse)(nil), // 1: pb.QueryRoomResponse
}
var file_rpc_query_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_query_room_proto_init() }
func file_rpc_query_room_proto_init() {
	if File_rpc_query_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_query_room_proto_rawDesc), len(file_rpc_query_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_query_room_proto_goTypes,
		DependencyIndexes: file_rpc_query_room_proto_depIdxs,
		MessageInfos:      file_rpc_query_room_proto_msgTypes,
	}.Build()
	File_rpc_query_room_proto = out.File
	file_rpc_query_room_proto_goTypes = nil
	file_rpc_query_room_proto_depIdxs = nil
}
