// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpc_query_area.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAreaRequest) Reset() {
	*x = QueryAreaRequest{}
	mi := &file_rpc_query_area_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAreaRequest) ProtoMessage() {}

func (x *QueryAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_area_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAreaRequest.ProtoReflect.Descriptor instead.
func (*QueryAreaRequest) Descriptor() ([]byte, []int) {
	return file_rpc_query_area_proto_rawDescGZIP(), []int{0}
}

type QueryAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // 原始的 JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAreaResponse) Reset() {
	*x = QueryAreaResponse{}
	mi := &file_rpc_query_area_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAreaResponse) ProtoMessage() {}

func (x *QueryAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_query_area_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAreaResponse.ProtoReflect.Descriptor instead.
func (*QueryAreaResponse) Descriptor() ([]byte, []int) {
	return file_rpc_query_area_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAreaResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_rpc_query_area_proto protoreflect.FileDescriptor

const file_rpc_query_area_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_query_area.proto\x12\x02pb\"\x12\n" +
	"\x10QueryAreaRequest\"0\n" +
	"\x11QueryAreaResponse\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonDataB\"Z github.com/Jingqi0327/eleclog/pbb\x06proto3"

var (
	file_rpc_query_area_proto_rawDescOnce sync.Once
	file_rpc_query_area_proto_rawDescData []byte
)

func file_rpc_query_area_proto_rawDescGZIP() []byte {
	file_rpc_query_area_proto_rawDescOnce.Do(func() {
		file_rpc_query_area_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_query_area_proto_rawDesc), len(file_rpc_query_area_proto_rawDesc)))
	})
	return file_rpc_query_area_proto_rawDescData
}

var file_rpc_query_area_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_query_area_proto_goTypes = []any{
	(*QueryAreaRequest)(nil),  // 0: pb.QueryAreaRequest
	(*QueryAreaResponse)(nil), // 1: pb.QueryAreaResponse
}
var file_rpc_query_area_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_query_area_proto_init() }
func file_rpc_query_area_proto_init() {
	if File_rpc_query_area_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_query_area_proto_rawDesc), len(file_rpc_query_area_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_query_area_proto_goTypes,
		DependencyIndexes: file_rpc_query_area_proto_depIdxs,
		MessageInfos:      file_rpc_query_area_proto_msgTypes,
	}.Build()
	File_rpc_query_area_proto = out.File
	file_rpc_query_area_proto_goTypes = nil
	file_rpc_query_area_proto_depIdxs = nil
}
