// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service_proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proxy_proto protoreflect.FileDescriptor

const file_service_proxy_proto_rawDesc = "" +
	"\n" +
	"\x13service_proxy.proto\x12\x02pb\x1a\x14rpc_query_area.proto\x1a\x18rpc_query_building.proto\x1a\x15rpc_query_floor.proto\x1a\x14rpc_query_room.proto\x1a\x1crpc_query_room_surplus.proto2\xde\x02\n" +
	"\fProxyService\x12:\n" +
	"\tQueryArea\x12\x14.pb.QueryAreaRequest\x1a\x15.pb.QueryAreaResponse\"\x00\x12F\n" +
	"\rQueryBuilding\x12\x18.pb.QueryBuildingRequest\x1a\x19.pb.QueryBuildingResponse\"\x00\x12=\n" +
	"\n" +
	"QueryFloor\x12\x15.pb.QueryFloorRequest\x1a\x16.pb.QueryFloorResponse\"\x00\x12:\n" +
	"\tQueryRoom\x12\x14.pb.QueryRoomRequest\x1a\x15.pb.QueryRoomResponse\"\x00\x12O\n" +
	"\x10QueryRoomSurplus\x12\x1b.pb.QueryRoomSurplusRequest\x1a\x1c.pb.QueryRoomSurplusResponse\"\x00B\"Z github.com/Jingqi0327/eleclog/pbb\x06proto3"

var file_service_proxy_proto_goTypes = []any{
	(*QueryAreaRequest)(nil),         // 0: pb.QueryAreaRequest
	(*QueryBuildingRequest)(nil),     // 1: pb.QueryBuildingRequest
	(*QueryFloorRequest)(nil),        // 2: pb.QueryFloorRequest
	(*QueryRoomRequest)(nil),         // 3: pb.QueryRoomRequest
	(*QueryRoomSurplusRequest)(nil),  // 4: pb.QueryRoomSurplusRequest
	(*QueryAreaResponse)(nil),        // 5: pb.QueryAreaResponse
	(*QueryBuildingResponse)(nil),    // 6: pb.QueryBuildingResponse
	(*QueryFloorResponse)(nil),       // 7: pb.QueryFloorResponse
	(*QueryRoomResponse)(nil),        // 8: pb.QueryRoomResponse
	(*QueryRoomSurplusResponse)(nil), // 9: pb.QueryRoomSurplusResponse
}
var file_service_proxy_proto_depIdxs = []int32{
	0, // 0: pb.ProxyService.QueryArea:input_type -> pb.QueryAreaRequest
	1, // 1: pb.ProxyService.QueryBuilding:input_type -> pb.QueryBuildingRequest
	2, // 2: pb.ProxyService.QueryFloor:input_type -> pb.QueryFloorRequest
	3, // 3: pb.ProxyService.QueryRoom:input_type -> pb.QueryRoomRequest
	4, // 4: pb.ProxyService.QueryRoomSurplus:input_type -> pb.QueryRoomSurplusRequest
	5, // 5: pb.ProxyService.QueryArea:output_type -> pb.QueryAreaResponse
	6, // 6: pb.ProxyService.QueryBuilding:output_type -> pb.QueryBuildingResponse
	7, // 7: pb.ProxyService.QueryFloor:output_type -> pb.QueryFloorResponse
	8, // 8: pb.ProxyService.QueryRoom:output_type -> pb.QueryRoomResponse
	9, // 9: pb.ProxyService.QueryRoomSurplus:output_type -> pb.QueryRoomSurplusResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proxy_proto_init() }
func file_service_proxy_proto_init() {
	if File_service_proxy_proto != nil {
		return
	}
	file_rpc_query_area_proto_init()
	file_rpc_query_building_proto_init()
	file_rpc_query_floor_proto_init()
	file_rpc_query_room_proto_init()
	file_rpc_query_room_surplus_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proxy_proto_rawDesc), len(file_service_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proxy_proto_goTypes,
		DependencyIndexes: file_service_proxy_proto_depIdxs,
	}.Build()
	File_service_proxy_proto = out.File
	file_service_proxy_proto_goTypes = nil
	file_service_proxy_proto_depIdxs = nil
}
