// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: service_proxy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyService_QueryArea_FullMethodName        = "/pb.ProxyService/QueryArea"
	ProxyService_QueryBuilding_FullMethodName    = "/pb.ProxyService/QueryBuilding"
	ProxyService_QueryFloor_FullMethodName       = "/pb.ProxyService/QueryFloor"
	ProxyService_QueryRoom_FullMethodName        = "/pb.ProxyService/QueryRoom"
	ProxyService_QueryRoomSurplus_FullMethodName = "/pb.ProxyService/QueryRoomSurplus"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyServiceClient interface {
	QueryArea(ctx context.Context, in *QueryAreaRequest, opts ...grpc.CallOption) (*QueryAreaResponse, error)
	QueryBuilding(ctx context.Context, in *QueryBuildingRequest, opts ...grpc.CallOption) (*QueryBuildingResponse, error)
	QueryFloor(ctx context.Context, in *QueryFloorRequest, opts ...grpc.CallOption) (*QueryFloorResponse, error)
	QueryRoom(ctx context.Context, in *QueryRoomRequest, opts ...grpc.CallOption) (*QueryRoomResponse, error)
	QueryRoomSurplus(ctx context.Context, in *QueryRoomSurplusRequest, opts ...grpc.CallOption) (*QueryRoomSurplusResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) QueryArea(ctx context.Context, in *QueryAreaRequest, opts ...grpc.CallOption) (*QueryAreaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAreaResponse)
	err := c.cc.Invoke(ctx, ProxyService_QueryArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) QueryBuilding(ctx context.Context, in *QueryBuildingRequest, opts ...grpc.CallOption) (*QueryBuildingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBuildingResponse)
	err := c.cc.Invoke(ctx, ProxyService_QueryBuilding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) QueryFloor(ctx context.Context, in *QueryFloorRequest, opts ...grpc.CallOption) (*QueryFloorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFloorResponse)
	err := c.cc.Invoke(ctx, ProxyService_QueryFloor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) QueryRoom(ctx context.Context, in *QueryRoomRequest, opts ...grpc.CallOption) (*QueryRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoomResponse)
	err := c.cc.Invoke(ctx, ProxyService_QueryRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) QueryRoomSurplus(ctx context.Context, in *QueryRoomSurplusRequest, opts ...grpc.CallOption) (*QueryRoomSurplusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoomSurplusResponse)
	err := c.cc.Invoke(ctx, ProxyService_QueryRoomSurplus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
type ProxyServiceServer interface {
	QueryArea(context.Context, *QueryAreaRequest) (*QueryAreaResponse, error)
	QueryBuilding(context.Context, *QueryBuildingRequest) (*QueryBuildingResponse, error)
	QueryFloor(context.Context, *QueryFloorRequest) (*QueryFloorResponse, error)
	QueryRoom(context.Context, *QueryRoomRequest) (*QueryRoomResponse, error)
	QueryRoomSurplus(context.Context, *QueryRoomSurplusRequest) (*QueryRoomSurplusResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) QueryArea(context.Context, *QueryAreaRequest) (*QueryAreaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryArea not implemented")
}
func (UnimplementedProxyServiceServer) QueryBuilding(context.Context, *QueryBuildingRequest) (*QueryBuildingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryBuilding not implemented")
}
func (UnimplementedProxyServiceServer) QueryFloor(context.Context, *QueryFloorRequest) (*QueryFloorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryFloor not implemented")
}
func (UnimplementedProxyServiceServer) QueryRoom(context.Context, *QueryRoomRequest) (*QueryRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRoom not implemented")
}
func (UnimplementedProxyServiceServer) QueryRoomSurplus(context.Context, *QueryRoomSurplusRequest) (*QueryRoomSurplusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRoomSurplus not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_QueryArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).QueryArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_QueryArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).QueryArea(ctx, req.(*QueryAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_QueryBuilding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBuildingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).QueryBuilding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_QueryBuilding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).QueryBuilding(ctx, req.(*QueryBuildingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_QueryFloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFloorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).QueryFloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_QueryFloor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).QueryFloor(ctx, req.(*QueryFloorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_QueryRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).QueryRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_QueryRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).QueryRoom(ctx, req.(*QueryRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_QueryRoomSurplus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRoomSurplusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).QueryRoomSurplus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_QueryRoomSurplus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).QueryRoomSurplus(ctx, req.(*QueryRoomSurplusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryArea",
			Handler:    _ProxyService_QueryArea_Handler,
		},
		{
			MethodName: "QueryBuilding",
			Handler:    _ProxyService_QueryBuilding_Handler,
		},
		{
			MethodName: "QueryFloor",
			Handler:    _ProxyService_QueryFloor_Handler,
		},
		{
			MethodName: "QueryRoom",
			Handler:    _ProxyService_QueryRoom_Handler,
		},
		{
			MethodName: "QueryRoomSurplus",
			Handler:    _ProxyService_QueryRoomSurplus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_proxy.proto",
}
