// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jingqi0327/eleclog/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/Jingqi0327/eleclog/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CountRooms mocks base method.
func (m *MockStore) CountRooms(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRooms", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRooms indicates an expected call of CountRooms.
func (mr *MockStoreMockRecorder) CountRooms(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRooms", reflect.TypeOf((*MockStore)(nil).CountRooms), arg0)
}

// CountUserRoomNotifications mocks base method.
func (m *MockStore) CountUserRoomNotifications(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserRoomNotifications", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserRoomNotifications indicates an expected call of CountUserRoomNotifications.
func (mr *MockStoreMockRecorder) CountUserRoomNotifications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserRoomNotifications", reflect.TypeOf((*MockStore)(nil).CountUserRoomNotifications), arg0)
}

// CountUsers mocks base method.
func (m *MockStore) CountUsers(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStoreMockRecorder) CountUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), arg0)
}

// CreateElectricityRecord mocks base method.
func (m *MockStore) CreateElectricityRecord(arg0 context.Context, arg1 db.CreateElectricityRecordParams) (db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateElectricityRecord", arg0, arg1)
	ret0, _ := ret[0].(db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateElectricityRecord indicates an expected call of CreateElectricityRecord.
func (mr *MockStoreMockRecorder) CreateElectricityRecord(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateElectricityRecord", reflect.TypeOf((*MockStore)(nil).CreateElectricityRecord), arg0, arg1)
}

// CreateElectricityRecordwithTime mocks base method.
func (m *MockStore) CreateElectricityRecordwithTime(arg0 context.Context, arg1 db.CreateElectricityRecordwithTimeParams) (db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateElectricityRecordwithTime", arg0, arg1)
	ret0, _ := ret[0].(db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateElectricityRecordwithTime indicates an expected call of CreateElectricityRecordwithTime.
func (mr *MockStoreMockRecorder) CreateElectricityRecordwithTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateElectricityRecordwithTime", reflect.TypeOf((*MockStore)(nil).CreateElectricityRecordwithTime), arg0, arg1)
}

// CreateRoom mocks base method.
func (m *MockStore) CreateRoom(arg0 context.Context, arg1 db.CreateRoomParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockStoreMockRecorder) CreateRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockStore)(nil).CreateRoom), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserRoomNotification mocks base method.
func (m *MockStore) CreateUserRoomNotification(arg0 context.Context, arg1 db.CreateUserRoomNotificationParams) (db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRoomNotification", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserRoomNotification indicates an expected call of CreateUserRoomNotification.
func (mr *MockStoreMockRecorder) CreateUserRoomNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRoomNotification", reflect.TypeOf((*MockStore)(nil).CreateUserRoomNotification), arg0, arg1)
}

// DeleteRoom mocks base method.
func (m *MockStore) DeleteRoom(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockStoreMockRecorder) DeleteRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockStore)(nil).DeleteRoom), arg0, arg1)
}

// DeleteUserRoomNotification mocks base method.
func (m *MockStore) DeleteUserRoomNotification(arg0 context.Context, arg1 db.DeleteUserRoomNotificationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRoomNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRoomNotification indicates an expected call of DeleteUserRoomNotification.
func (mr *MockStoreMockRecorder) DeleteUserRoomNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRoomNotification", reflect.TypeOf((*MockStore)(nil).DeleteUserRoomNotification), arg0, arg1)
}

// GetLatestBalance mocks base method.
func (m *MockStore) GetLatestBalance(arg0 context.Context, arg1 int64) (db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBalance", arg0, arg1)
	ret0, _ := ret[0].(db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBalance indicates an expected call of GetLatestBalance.
func (mr *MockStoreMockRecorder) GetLatestBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBalance", reflect.TypeOf((*MockStore)(nil).GetLatestBalance), arg0, arg1)
}

// GetRecordedAtsByRange mocks base method.
func (m *MockStore) GetRecordedAtsByRange(arg0 context.Context, arg1 db.GetRecordedAtsByRangeParams) ([]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordedAtsByRange", arg0, arg1)
	ret0, _ := ret[0].([]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordedAtsByRange indicates an expected call of GetRecordedAtsByRange.
func (mr *MockStoreMockRecorder) GetRecordedAtsByRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordedAtsByRange", reflect.TypeOf((*MockStore)(nil).GetRecordedAtsByRange), arg0, arg1)
}

// GetRecordsByHourRange mocks base method.
func (m *MockStore) GetRecordsByHourRange(arg0 context.Context, arg1 db.GetRecordsByHourRangeParams) ([]db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByHourRange", arg0, arg1)
	ret0, _ := ret[0].([]db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByHourRange indicates an expected call of GetRecordsByHourRange.
func (mr *MockStoreMockRecorder) GetRecordsByHourRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByHourRange", reflect.TypeOf((*MockStore)(nil).GetRecordsByHourRange), arg0, arg1)
}

// GetRoom mocks base method.
func (m *MockStore) GetRoom(arg0 context.Context, arg1 int64) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockStoreMockRecorder) GetRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockStore)(nil).GetRoom), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserRoomNotification mocks base method.
func (m *MockStore) GetUserRoomNotification(arg0 context.Context, arg1 db.GetUserRoomNotificationParams) (db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoomNotification", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoomNotification indicates an expected call of GetUserRoomNotification.
func (mr *MockStoreMockRecorder) GetUserRoomNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoomNotification", reflect.TypeOf((*MockStore)(nil).GetUserRoomNotification), arg0, arg1)
}

// ListDueUserRoomNotifications mocks base method.
func (m *MockStore) ListDueUserRoomNotifications(arg0 context.Context) ([]db.ListDueUserRoomNotificationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDueUserRoomNotifications", arg0)
	ret0, _ := ret[0].([]db.ListDueUserRoomNotificationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDueUserRoomNotifications indicates an expected call of ListDueUserRoomNotifications.
func (mr *MockStoreMockRecorder) ListDueUserRoomNotifications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDueUserRoomNotifications", reflect.TypeOf((*MockStore)(nil).ListDueUserRoomNotifications), arg0)
}

// ListRooms mocks base method.
func (m *MockStore) ListRooms(arg0 context.Context, arg1 db.ListRoomsParams) ([]db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", arg0, arg1)
	ret0, _ := ret[0].([]db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockStoreMockRecorder) ListRooms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockStore)(nil).ListRooms), arg0, arg1)
}

// ListRoomsAll mocks base method.
func (m *MockStore) ListRoomsAll(arg0 context.Context) ([]db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsAll", arg0)
	ret0, _ := ret[0].([]db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsAll indicates an expected call of ListRoomsAll.
func (mr *MockStoreMockRecorder) ListRoomsAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsAll", reflect.TypeOf((*MockStore)(nil).ListRoomsAll), arg0)
}

// ListUserRoomNotifications mocks base method.
func (m *MockStore) ListUserRoomNotifications(arg0 context.Context, arg1 db.ListUserRoomNotificationsParams) ([]db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoomNotifications", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoomNotifications indicates an expected call of ListUserRoomNotifications.
func (mr *MockStoreMockRecorder) ListUserRoomNotifications(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoomNotifications", reflect.TypeOf((*MockStore)(nil).ListUserRoomNotifications), arg0, arg1)
}

// ListUserRoomNotificationsByRoom mocks base method.
func (m *MockStore) ListUserRoomNotificationsByRoom(arg0 context.Context, arg1 int64) ([]db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoomNotificationsByRoom", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoomNotificationsByRoom indicates an expected call of ListUserRoomNotificationsByRoom.
func (mr *MockStoreMockRecorder) ListUserRoomNotificationsByRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoomNotificationsByRoom", reflect.TypeOf((*MockStore)(nil).ListUserRoomNotificationsByRoom), arg0, arg1)
}

// ListUserRoomNotificationsByUser mocks base method.
func (m *MockStore) ListUserRoomNotificationsByUser(arg0 context.Context, arg1 string) ([]db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoomNotificationsByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoomNotificationsByUser indicates an expected call of ListUserRoomNotificationsByUser.
func (mr *MockStoreMockRecorder) ListUserRoomNotificationsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoomNotificationsByUser", reflect.TypeOf((*MockStore)(nil).ListUserRoomNotificationsByUser), arg0, arg1)
}

// UpdateRoom mocks base method.
func (m *MockStore) UpdateRoom(arg0 context.Context, arg1 db.UpdateRoomParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoom indicates an expected call of UpdateRoom.
func (mr *MockStoreMockRecorder) UpdateRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoom", reflect.TypeOf((*MockStore)(nil).UpdateRoom), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserRoomNotification mocks base method.
func (m *MockStore) UpdateUserRoomNotification(arg0 context.Context, arg1 db.UpdateUserRoomNotificationParams) (db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoomNotification", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRoomNotification indicates an expected call of UpdateUserRoomNotification.
func (mr *MockStoreMockRecorder) UpdateUserRoomNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoomNotification", reflect.TypeOf((*MockStore)(nil).UpdateUserRoomNotification), arg0, arg1)
}

// UpdateUserRoomNotificationLastNotifiedAt mocks base method.
func (m *MockStore) UpdateUserRoomNotificationLastNotifiedAt(arg0 context.Context, arg1 db.UpdateUserRoomNotificationLastNotifiedAtParams) (db.UserRoomNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoomNotificationLastNotifiedAt", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoomNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRoomNotificationLastNotifiedAt indicates an expected call of UpdateUserRoomNotificationLastNotifiedAt.
func (mr *MockStoreMockRecorder) UpdateUserRoomNotificationLastNotifiedAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoomNotificationLastNotifiedAt", reflect.TypeOf((*MockStore)(nil).UpdateUserRoomNotificationLastNotifiedAt), arg0, arg1)
}
