// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jingqi0327/eleclog/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/Jingqi0327/eleclog/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// BindRoomToUserTx mocks base method.
func (m *MockStore) BindRoomToUserTx(arg0 context.Context, arg1 db.BindRoomToUserTxParams) (db.BindRoomToUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindRoomToUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.BindRoomToUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BindRoomToUserTx indicates an expected call of BindRoomToUserTx.
func (mr *MockStoreMockRecorder) BindRoomToUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindRoomToUserTx", reflect.TypeOf((*MockStore)(nil).BindRoomToUserTx), arg0, arg1)
}

// CountRooms mocks base method.
func (m *MockStore) CountRooms(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRooms", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRooms indicates an expected call of CountRooms.
func (mr *MockStoreMockRecorder) CountRooms(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRooms", reflect.TypeOf((*MockStore)(nil).CountRooms), arg0)
}

// CountRoomsByUser mocks base method.
func (m *MockStore) CountRoomsByUser(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRoomsByUser", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRoomsByUser indicates an expected call of CountRoomsByUser.
func (mr *MockStoreMockRecorder) CountRoomsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRoomsByUser", reflect.TypeOf((*MockStore)(nil).CountRoomsByUser), arg0, arg1)
}

// CountUserRooms mocks base method.
func (m *MockStore) CountUserRooms(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserRooms", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserRooms indicates an expected call of CountUserRooms.
func (mr *MockStoreMockRecorder) CountUserRooms(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserRooms", reflect.TypeOf((*MockStore)(nil).CountUserRooms), arg0)
}

// CountUsers mocks base method.
func (m *MockStore) CountUsers(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStoreMockRecorder) CountUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), arg0)
}

// CreateElectricityRecord mocks base method.
func (m *MockStore) CreateElectricityRecord(arg0 context.Context, arg1 db.CreateElectricityRecordParams) (db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateElectricityRecord", arg0, arg1)
	ret0, _ := ret[0].(db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateElectricityRecord indicates an expected call of CreateElectricityRecord.
func (mr *MockStoreMockRecorder) CreateElectricityRecord(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateElectricityRecord", reflect.TypeOf((*MockStore)(nil).CreateElectricityRecord), arg0, arg1)
}

// CreateElectricityRecordwithTime mocks base method.
func (m *MockStore) CreateElectricityRecordwithTime(arg0 context.Context, arg1 db.CreateElectricityRecordwithTimeParams) (db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateElectricityRecordwithTime", arg0, arg1)
	ret0, _ := ret[0].(db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateElectricityRecordwithTime indicates an expected call of CreateElectricityRecordwithTime.
func (mr *MockStoreMockRecorder) CreateElectricityRecordwithTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateElectricityRecordwithTime", reflect.TypeOf((*MockStore)(nil).CreateElectricityRecordwithTime), arg0, arg1)
}

// CreateRoom mocks base method.
func (m *MockStore) CreateRoom(arg0 context.Context, arg1 db.CreateRoomParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockStoreMockRecorder) CreateRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockStore)(nil).CreateRoom), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserRoom mocks base method.
func (m *MockStore) CreateUserRoom(arg0 context.Context, arg1 db.CreateUserRoomParams) (db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRoom", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserRoom indicates an expected call of CreateUserRoom.
func (mr *MockStoreMockRecorder) CreateUserRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRoom", reflect.TypeOf((*MockStore)(nil).CreateUserRoom), arg0, arg1)
}

// DeleteRoom mocks base method.
func (m *MockStore) DeleteRoom(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockStoreMockRecorder) DeleteRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockStore)(nil).DeleteRoom), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// DeleteUserRoom mocks base method.
func (m *MockStore) DeleteUserRoom(arg0 context.Context, arg1 db.DeleteUserRoomParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRoom indicates an expected call of DeleteUserRoom.
func (mr *MockStoreMockRecorder) DeleteUserRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRoom", reflect.TypeOf((*MockStore)(nil).DeleteUserRoom), arg0, arg1)
}

// GetLatestBalance mocks base method.
func (m *MockStore) GetLatestBalance(arg0 context.Context, arg1 int64) (db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBalance", arg0, arg1)
	ret0, _ := ret[0].(db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBalance indicates an expected call of GetLatestBalance.
func (mr *MockStoreMockRecorder) GetLatestBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBalance", reflect.TypeOf((*MockStore)(nil).GetLatestBalance), arg0, arg1)
}

// GetRecordedAtsByRange mocks base method.
func (m *MockStore) GetRecordedAtsByRange(arg0 context.Context, arg1 db.GetRecordedAtsByRangeParams) ([]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordedAtsByRange", arg0, arg1)
	ret0, _ := ret[0].([]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordedAtsByRange indicates an expected call of GetRecordedAtsByRange.
func (mr *MockStoreMockRecorder) GetRecordedAtsByRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordedAtsByRange", reflect.TypeOf((*MockStore)(nil).GetRecordedAtsByRange), arg0, arg1)
}

// GetRecordsByHourRange mocks base method.
func (m *MockStore) GetRecordsByHourRange(arg0 context.Context, arg1 db.GetRecordsByHourRangeParams) ([]db.ElectricityRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByHourRange", arg0, arg1)
	ret0, _ := ret[0].([]db.ElectricityRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByHourRange indicates an expected call of GetRecordsByHourRange.
func (mr *MockStoreMockRecorder) GetRecordsByHourRange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByHourRange", reflect.TypeOf((*MockStore)(nil).GetRecordsByHourRange), arg0, arg1)
}

// GetRoom mocks base method.
func (m *MockStore) GetRoom(arg0 context.Context, arg1 int64) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockStoreMockRecorder) GetRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockStore)(nil).GetRoom), arg0, arg1)
}

// GetRoomByCodes mocks base method.
func (m *MockStore) GetRoomByCodes(arg0 context.Context, arg1 db.GetRoomByCodesParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByCodes", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByCodes indicates an expected call of GetRoomByCodes.
func (mr *MockStoreMockRecorder) GetRoomByCodes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByCodes", reflect.TypeOf((*MockStore)(nil).GetRoomByCodes), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserRoom mocks base method.
func (m *MockStore) GetUserRoom(arg0 context.Context, arg1 db.GetUserRoomParams) (db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoom", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoom indicates an expected call of GetUserRoom.
func (mr *MockStoreMockRecorder) GetUserRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoom", reflect.TypeOf((*MockStore)(nil).GetUserRoom), arg0, arg1)
}

// ListDueUserRooms mocks base method.
func (m *MockStore) ListDueUserRooms(arg0 context.Context) ([]db.ListDueUserRoomsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDueUserRooms", arg0)
	ret0, _ := ret[0].([]db.ListDueUserRoomsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDueUserRooms indicates an expected call of ListDueUserRooms.
func (mr *MockStoreMockRecorder) ListDueUserRooms(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDueUserRooms", reflect.TypeOf((*MockStore)(nil).ListDueUserRooms), arg0)
}

// ListRooms mocks base method.
func (m *MockStore) ListRooms(arg0 context.Context, arg1 db.ListRoomsParams) ([]db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", arg0, arg1)
	ret0, _ := ret[0].([]db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockStoreMockRecorder) ListRooms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockStore)(nil).ListRooms), arg0, arg1)
}

// ListRoomsAll mocks base method.
func (m *MockStore) ListRoomsAll(arg0 context.Context) ([]db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsAll", arg0)
	ret0, _ := ret[0].([]db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsAll indicates an expected call of ListRoomsAll.
func (mr *MockStoreMockRecorder) ListRoomsAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsAll", reflect.TypeOf((*MockStore)(nil).ListRoomsAll), arg0)
}

// ListUserRoomDetails mocks base method.
func (m *MockStore) ListUserRoomDetails(arg0 context.Context, arg1 db.ListUserRoomDetailsParams) ([]db.ListUserRoomDetailsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoomDetails", arg0, arg1)
	ret0, _ := ret[0].([]db.ListUserRoomDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoomDetails indicates an expected call of ListUserRoomDetails.
func (mr *MockStoreMockRecorder) ListUserRoomDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoomDetails", reflect.TypeOf((*MockStore)(nil).ListUserRoomDetails), arg0, arg1)
}

// ListUserRooms mocks base method.
func (m *MockStore) ListUserRooms(arg0 context.Context, arg1 db.ListUserRoomsParams) ([]db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRooms", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRooms indicates an expected call of ListUserRooms.
func (mr *MockStoreMockRecorder) ListUserRooms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRooms", reflect.TypeOf((*MockStore)(nil).ListUserRooms), arg0, arg1)
}

// ListUserRoomsByRoom mocks base method.
func (m *MockStore) ListUserRoomsByRoom(arg0 context.Context, arg1 int64) ([]db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoomsByRoom", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoomsByRoom indicates an expected call of ListUserRoomsByRoom.
func (mr *MockStoreMockRecorder) ListUserRoomsByRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoomsByRoom", reflect.TypeOf((*MockStore)(nil).ListUserRoomsByRoom), arg0, arg1)
}

// ListUserRoomsByUser mocks base method.
func (m *MockStore) ListUserRoomsByUser(arg0 context.Context, arg1 db.ListUserRoomsByUserParams) ([]db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserRoomsByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserRoomsByUser indicates an expected call of ListUserRoomsByUser.
func (mr *MockStoreMockRecorder) ListUserRoomsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserRoomsByUser", reflect.TypeOf((*MockStore)(nil).ListUserRoomsByUser), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(arg0 context.Context, arg1 db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), arg0, arg1)
}

// UpdateRoom mocks base method.
func (m *MockStore) UpdateRoom(arg0 context.Context, arg1 db.UpdateRoomParams) (db.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoom", arg0, arg1)
	ret0, _ := ret[0].(db.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoom indicates an expected call of UpdateRoom.
func (mr *MockStoreMockRecorder) UpdateRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoom", reflect.TypeOf((*MockStore)(nil).UpdateRoom), arg0, arg1)
}

// UpdateRoomLastNotifiedAtTx mocks base method.
func (m *MockStore) UpdateRoomLastNotifiedAtTx(arg0 context.Context, arg1 db.UpdateUserRoomLastNotifiedAtTxParams) (db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomLastNotifiedAtTx", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoomLastNotifiedAtTx indicates an expected call of UpdateRoomLastNotifiedAtTx.
func (mr *MockStoreMockRecorder) UpdateRoomLastNotifiedAtTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomLastNotifiedAtTx", reflect.TypeOf((*MockStore)(nil).UpdateRoomLastNotifiedAtTx), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserRoom mocks base method.
func (m *MockStore) UpdateUserRoom(arg0 context.Context, arg1 db.UpdateUserRoomParams) (db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoom", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRoom indicates an expected call of UpdateUserRoom.
func (mr *MockStoreMockRecorder) UpdateUserRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoom", reflect.TypeOf((*MockStore)(nil).UpdateUserRoom), arg0, arg1)
}

// UpdateUserRoomLastNotifiedAt mocks base method.
func (m *MockStore) UpdateUserRoomLastNotifiedAt(arg0 context.Context, arg1 db.UpdateUserRoomLastNotifiedAtParams) (db.UserRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoomLastNotifiedAt", arg0, arg1)
	ret0, _ := ret[0].(db.UserRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRoomLastNotifiedAt indicates an expected call of UpdateUserRoomLastNotifiedAt.
func (mr *MockStoreMockRecorder) UpdateUserRoomLastNotifiedAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoomLastNotifiedAt", reflect.TypeOf((*MockStore)(nil).UpdateUserRoomLastNotifiedAt), arg0, arg1)
}
